## library() calls go here
library(conflicted)
library(dotenv)
library(targets)
library(tarchetypes)

library(tidyverse)
library(tidylog)
library(haven)

conflict_prefer("add_count", "tidylog")
conflict_prefer("add_tally", "tidylog")
conflict_prefer("anti_join", "tidylog")
conflict_prefer("count", "tidylog")
conflict_prefer("distinct", "tidylog")
conflict_prefer("distinct_all", "tidylog")
conflict_prefer("distinct_at", "tidylog")
conflict_prefer("distinct_if", "tidylog")
conflict_prefer("drop_na", "tidylog")
conflict_prefer("fill", "tidylog")
conflict_prefer("filter", "tidylog")
conflict_prefer("filter_all", "tidylog")
conflict_prefer("filter_at", "tidylog")
conflict_prefer("filter_if", "tidylog")
conflict_prefer("full_join", "tidylog")
conflict_prefer("gather", "tidylog")
conflict_prefer("group_by", "tidylog")
conflict_prefer("group_by_all", "tidylog")
conflict_prefer("group_by_at", "tidylog")
conflict_prefer("group_by_if", "tidylog")
conflict_prefer("inner_join", "tidylog")
conflict_prefer("lag", "dplyr")
conflict_prefer("left_join", "tidylog")
conflict_prefer("mutate", "tidylog")
conflict_prefer("mutate_all", "tidylog")
conflict_prefer("mutate_at", "tidylog")
conflict_prefer("mutate_if", "tidylog")
conflict_prefer("pivot_longer", "tidylog")
conflict_prefer("pivot_wider", "tidylog")
conflict_prefer("Position", "ggplot2")
conflict_prefer("relocate", "tidylog")
conflict_prefer("rename", "tidylog")
conflict_prefer("rename_all", "tidylog")
conflict_prefer("rename_at", "tidylog")
conflict_prefer("rename_if", "tidylog")
conflict_prefer("rename_with", "tidylog")
conflict_prefer("replace_na", "tidylog")
conflict_prefer("right_join", "tidylog")
conflict_prefer("sample_frac", "tidylog")
conflict_prefer("sample_n", "tidylog")
conflict_prefer("select", "tidylog")
conflict_prefer("select_all", "tidylog")
conflict_prefer("select_at", "tidylog")
conflict_prefer("select_if", "tidylog")
conflict_prefer("semi_join", "tidylog")
conflict_prefer("slice", "tidylog")
conflict_prefer("slice_head", "tidylog")
conflict_prefer("slice_max", "tidylog")
conflict_prefer("slice_min", "tidylog")
conflict_prefer("slice_sample", "tidylog")
conflict_prefer("slice_tail", "tidylog")
conflict_prefer("spread", "tidylog")
conflict_prefer("summarise", "tidylog")
conflict_prefer("summarise_all", "tidylog")
conflict_prefer("summarise_at", "tidylog")
conflict_prefer("summarise_if", "tidylog")
conflict_prefer("summarize", "tidylog")
conflict_prefer("summarize_all", "tidylog")
conflict_prefer("summarize_at", "tidylog")
conflict_prefer("summarize_if", "tidylog")
conflict_prefer("tally", "tidylog")
conflict_prefer("top_frac", "tidylog")
conflict_prefer("top_n", "tidylog")
conflict_prefer("transmute", "tidylog")
conflict_prefer("transmute_all", "tidylog")
conflict_prefer("transmute_at", "tidylog")
conflict_prefer("transmute_if", "tidylog")
conflict_prefer("uncount", "tidylog")
conflict_prefer("ungroup", "tidylog")
